### ISSUE TITLE
Add upper bound for numpy version in dllib dependency

### ISSUE THREAD

**Issue by hkvision** [intel-analytics/BigDL#7548]
According to @hamham223 python 3.8 will default to install numpy 1.24, which will cause issues.
@hamham223 Paste the issues here and check what's the upper bound of the numpy we support.

**Comment by hamham223** [comment]
Previous Failed Job: [[Orca-Python-Ray-Py38-Spark3](https://github.com/intel-analytics/BigDL/actions/runs/3899906337/jobs/6660238794#logs)]

Typical Error Message:  `test/bigdl/orca/learn/ray/mxnet/test_mxnet_gluon.py` - AttributeError: module 'numpy' has no attribute 'bool'

This is due to [mxnet does not support numpy 1.24](https://github.com/apache/mxnet/issues/21165), although the installation requirement for mxnet 1.9.1 is `numpy<2.0.0,>1.16.0`. Hopefully they could fix this issue soon.

**Comment by hamham223** [comment]
Reference:
+ [Numpy 1.20 Deprecate](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations) the attributes `np.int`, `np.bool`, `np.float` etc.
+ [A long email](https://github.com/numpy/numpy/issues/22021) about the deprecation
+ [Deprecation is expired](https://github.com/numpy/numpy/pull/22607/files#diff-43b932a4beb6c6bc01b8cbb341d52dbc3d6d89c8f41ff044f66146489697171cR1) in numpy 1.24

**Comment by hamham223** [comment]
Two possible solutions?

1. add setup requirement: `numpy <= 1.23.5` 
2. replace all the `np.int` with `np.int32/64`, `np.float` with `np.float32/64`:

Here are all the **src** codes that have those deprecations

+ **dlib**:
    + https://github.com/intel-analytics/BigDL/blob/main/python/dllib/src/bigdl/dllib/models/rnn/rnnexample.py#L104
    + https://github.com/intel-analytics/BigDL/blob/main/python/dllib/src/bigdl/dllib/utils/utils.py#L227

+ **orca**:
    + https://github.com/intel-analytics/BigDL/blob/main/python/orca/src/bigdl/orca/learn/openvino/estimator.py#L145

+ **chronos**:
    + https://github.com/intel-analytics/BigDL/blob/main/python/chronos/src/bigdl/chronos/data/utils/roll_dataset.py#L34
    + https://github.com/intel-analytics/BigDL/blob/main/python/chronos/src/bigdl/chronos/model/tcmf/time.py#L62
    + https://github.com/intel-analytics/BigDL/blob/main/python/chronos/src/bigdl/chronos/model/tf1/VanillaLSTM_keras.py#L74

**Comment by hkvision** [comment]
> https://github.com/intel-analytics/BigDL/blob/main/python/dllib/src/bigdl/dllib/models/rnn/rnnexample.py#L104

can change to np.int32

> https://github.com/intel-analytics/BigDL/blob/main/python/dllib/src/bigdl/dllib/utils/utils.py#L227

can change to str

```
>>> np.array(["x"])
array(['x'], dtype='<U1')
>>> np.array(["x"]).astype(str)
array(['x'], dtype='<U1')
```

**Comment by hamham223** [comment]
Seems numpy 1.24 requires `np.array` must have homogeneous shape. e.g. `[[1,2], [3,4,5]]` is not acceptable. Previously numpy 1.21 does not have this problem.

https://stackoverflow.com/questions/67183501/setting-an-array-element-with-a-sequence-requested-array-has-an-inhomogeneous-sh

Failed job: https://github.com/intel-analytics/BigDL/actions/runs/4192715495/jobs/7268720402

**Comment by hkvision** [comment]
Fixed. Orca code/unit tests have now supported numpy 1.21

**Comment by sharan21** [comment]
I think this issue still persists. Are there any updates on this?

**Comment by hkvision** [comment]
Oh really? I think we have supported at least for numpy 1.24.

Can you provide us with more information? Including your numpy version, and what piece of code you get the issue. We will then look into this.
